# Generated by Django 6.0.8 on 2026-08-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_firstName', models.CharField(max_length=100)),
                ('emp_lastName', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_salary', models.FloatField()),
            ],
        ),
    ]
